### ISSUE TITLE
Specification of calibrated camera rotation

### ISSUE THREAD

**Issue by PaulDebus** [Pix4D/opf-spec#6]
Hello,
first of all a huge thank you for this initiative and publishing this open format. I think this is an important step forward for the photogrammetry community and should allow better collaboration.

I have a question/remark/request regarding the specification of rotations, for example for calibrated cameras, as described here:
https://pix4d.github.io/opf-spec/specification/calibrated_cameras.html#calibrated-camera

The OPF uses Euler angles, which [not all people like to use](https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible), me included. Would it be possible to allow using different ways to express those rotations, for example quaternions?

One issue I have with Euler angles is, that special care has to be taken when concatenating multiple rotations, for example when using [relative rigs](https://pix4d.github.io/opf-spec/specification/auxiliary_objects.html#rig-relatives), where quaternions can compute the global rotation by simple multiplication. Further, Euler angles have instabilities around looking straight up or down.

This is by no means a dealbreaker for me, just a comment and invitation for discussion. For many/most applications, this is probably fine, and I am still free to convert to quaternions in my application.

Thanks again and all the best
Paul Debus

**Comment by krahenbuhl** [comment]
Dear Paul,

Thank you for your kind words and your valuable feedback. We appreciate your support for the OPF initiative and your interest in enhancing the specification!

Regarding your question about using quaternions instead of Euler angles for expressing rotations, we carefully considered different alternatives during the design process of the OPF specification. While we understand that quaternions have certain advantages (avoiding gimbal lock and simplifying the concatenation of rotations), we opted to use Euler angles for several reasons.

One of the main considerations was the balance between simplicity and practicality. Euler angles are widely understood and used in the field of photogrammetry, making the specification more accessible to a broader range of users. Additionally, Euler angles can be easily converted to and from other rotation representations, including quaternions, allowing users like yourself to convert the rotations as needed in your specific applications.

We acknowledge that Euler angles may have some limitations, particularly when dealing with rotations near singularities, but for the majority of applications, they provide a straightforward and effective way to represent camera rotations within the OPF framework.

We appreciate your input and invite further discussion on this topic. Your feedback helps us refine and improve the OPF specification, ensuring its usability and effectiveness within the photogrammetry community.

Thank you once again for your support, and please feel free to reach out if you have any more questions or suggestions.
